[tool.mypy]
disallow_untyped_defs = true
warn_unused_ignores = true
ignore_missing_imports = false

[[tool.mypy.overrides]]
module = [
    "wechaty.*",
    "wechaty_puppet.*",
    "wechaty_plugin_contrib.*",
    "sqlalchemy.*",
    "sqlalchemy.orm.*",
    "sqlalchemy.ext.asyncio.*",
    "apscheduler.schedulers.base.*",
    "apscheduler.schedulers.asyncio.*",
    "wechaty_grpc.wechaty.puppet.*"
]
ignore_missing_imports = true


# refer to: https://docs.pytest.org/en/stable/mark.html
[tool.pytest.ini_options]
pythonpath = "src"
minversion = "6.0"
testpaths = [
    "tests"
]